name: Arcanum Primus
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Your Friendly Neighborhood Witch.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72441609-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffb'
    - '#030200'
    - '#ff5700'
    - '#6a0900'
    - '#fdd674'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
