name: Arcanum Primus
favicon: null
layout_spectrum: 1
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffb'
    - '#030200'
    - '#ff5700'
    - '#6a0900'
    - '#fdd674'
  brandStrength: 0.25
  lightness: 0.0625
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
